[build]
  command = "jekyll build"
  publish = "_site"

[context.production.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/docs"
  to = "/docs/current/"

[[redirects]]
  from = "/docs/*"
  to = "https://prestosql-docs.netlify.com/:splat"
  status = 200
