[build]
  command = "jekyll build"
  publish = "_site"

[context.production.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/blog/assets/*"
  to = "/assets/blog/:splat"

[[redirects]]
  from = "/docs"
  to = "/docs/current/"

[[redirects]]
  from = "/docs/*"
  to = "https://prestosql.github.io/docs.prestosql.io/:splat"
  status = 200
